name: stuff_accounting_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.1.1
  flutter: 
    sdk: flutter
  crypto: ^3.0.2
  http: ^0.13.5
  barcode_scan2: ^4.2.4
  uuid: ^3.0.7

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.13.0"

flutter_icons:
  ios: true
  image_path: "assets/img/icon.png"

flutter: 
  uses-material-design: true

